# Generated by Django 2.2.7 on 2019-11-22 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_customtext_dada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1', models.BigIntegerField()),
                ('f2', models.BinaryField()),
                ('f3', models.BooleanField()),
                ('f4', models.CharField(max_length=256)),
                ('f5', models.DateField()),
                ('f6', models.DateTimeField()),
                ('f7', models.DurationField()),
                ('f9', models.EmailField(max_length=254)),
                ('f10', models.FloatField()),
                ('f11', models.IntegerField()),
                ('f13', models.PositiveIntegerField()),
                ('f14', models.PositiveSmallIntegerField()),
                ('f16', models.SmallIntegerField()),
                ('f17', models.TextField()),
                ('f19', models.URLField()),
                ('f20', models.UUIDField()),
                ('f8', models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True)),
                ('f18', models.TimeField(blank=True, null=True)),
                ('f15', models.SlugField(blank=True, null=True)),
                ('f21', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_f21', to='home.CustomText')),
                ('f22', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_f22', to='home.HomePage')),
                ('f23', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_f23', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
