# Generated by Django 2.2.7 on 2019-11-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='f00',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
